gems:
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-paginate
  - 'jekyll-admin'
exclude:
  - /vendor/
title: Cracker
subtitle: Know yourself. Face fear. Follow heart and Make Change
email: jwhyun2215@gmail.com
name: Hyun Jinwoo
description: |
  Know yourself. Face fear. Follow heart and Make Change
baseurl: /
url: 'https://github.com/PrimadonnaGit/PrimadonnaGit.github.io'
cover: /assets/header_image.jpg
logo: /assets/cracker_logo.png
markdown: kramdown
paginate: 5
paginate_path: '/page:num/'
inter_post_navigation: false
highlightjs_theme: monokai-sublime
jekyll-archives:
  enabled:
    - categories
    - tags
  layout: archive
  permalinks:
    category: '/category/:name/'
    tag: '/tag/:name/'
descriptions: []
social:
  - name: GitHub
    icon: github
    username: primadonna
    url: 'https://github.com/PrimadonnaGit/PrimadonnaGit.github.io'
    desc: Fork me on GitHub
    share: false
protocols:
  fb_image: /assets/cracker_logo.png
  fb_image_width: 612
  fb_image_height: 605
  fb_image_type: image/png
