# External gems
# See http://ixti.net/software/2013/01/28/using-jekyll-plugins-on-github-pages.html for making `jekyll archives` work.
gems:
  - jekyll-archives # Sorry, not GitHub pages friendly!
  - jekyll-sitemap
  - jekyll-paginate

exclude:
  - "/vendor/"

# Site settings
title: We are Cracker
subtitle: "크래커 기술 블로그"
email: jwhyun2215@gmail.com
name: Hyun Jinwoo
description: >
  Know yourself. Face fear. Follow heart and Make change
  
# Base URL of site (i.e. /blog). It should always start with a slash,
# and never end with a slash. Set it to a blank value if hosting at the
# root of your server.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://PrimadonnaGit.github.io" # the base hostname & protocol for your site
cover: "/assets/header_image.jpg"
logo: "/assets/cracker_logo.png"

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
inter_post_navigation: false
highlightjs_theme: "monokai-sublime"

# Archive settings (see https://github.com/jekyll/jekyll-archives/)
jekyll-archives:
  enabled:
    - categories
    - subcats
    - tags
  layout: 'archive'
  permalinks:
    category: '/category/:name/'
    tag: '/tag/:name/'
    subcats: '/subcats/:name/'
    
# Disqus comments
# disqus_shortname: bencentra

# Google analytics
# ga_tracking_id: "UA-XXXX-1"

# Category descriptions (for archive pages)
descriptions:
  - cat: deeplearning
    desc: "Posts describing DeepLearning techniques."

  - cat: elasticsearch
    desc: "Posts describing ElasticSearch techniques."

  - cat: nlp
    desc: "Posts describing NLP techniques."

# Social icons and sharing options
#
# Social settings are used in two places:
# * In the footer, as links to your personal profiles
# * After each blog post for sharing widgets
#
# Example:
#
# social:
#   - name: Twitter                         # Name of the service
#     icon: twitter                         # Font Awesome icon to use (minus fa- prefix)
#     username: "@TheBenCentra"             # (User) Name to display in the footer link
#     url: https://twitter.com/TheBenCentra # URL of your profile (leave blank to not display in footer)
#     desc: Follow me on Twitter            # Description to display as link title, etc
#     share: true                           # Include in the "Share" section of posts

social:
  - name: GitHub
    icon: github
    username: PrimadonnaGit
    url: https://github.com/PrimadonnaGit
    desc: Fork me on GitHub
    share: True

  - name: Facebook
    icon: facebook
    username: primadonnaf
    url: https://www.facebook.com/primadonnaf
    desc: Friend me on Facebook
    share: true

# Social sharing protocols
# These are for automatically generating sharing metadata for FB and Twitter
# OS Protocol is for sharing the source of your site, if you're interested. For more, see osprotocol.com
protocols:
    fb_image: "/assets/cracker_logo.png"
    fb_image_width: 612
    fb_image_height: 605
    fb_image_type: "image/png"
